### ISSUE TITLE
Question ouverte JDS : gestion visuels / diaporama

### ISSUE THREAD

**Issue by Julie-JDS** [Jardin-des-Sciences/website#1]
Lors de notre échange avec Béatrice, nous avons identifié une question : 

> Comment allons-nous gérer les visuels et les diaporamas ? 

Un billet comporte des visuels. Une fois ce billet dans un dossier, les visuels associés le suivent.
Ils sont donc visibles de façon autonome par rapport au billet et cohabitent avec les diaporamas ?
Ou alors ces visuels ne sont-ils visibles que dans le billets et non pas en dehors, en vrac dans le dossier.
Dans ce cas, on n'a pas de soucis vis à vis des diaporamas.

Béatrice demandait s'il doit y avoir un type de contenu diaporama, ou si les diaporama seront générés dynamiquement lorsque plusieurs visuels seront associés à un dossier ou à un billet ?

> Une hypothèse : est-ce qu'il serait judicieux de prévoir des édito rattachés aux diaporamas. 
Est ce que ça en fait des dossiers dans ce cas... ?

**Comment by bzg** [comment]
Comme discuté le 2 novembre 2015, l'idée est de garder un type de contenu "diaporama" qui soit au plus proche du fichier de diaporama (pdf, ppt, pptx) lui-même.  Sinon le risque est que ce type de contenu se rapproche trop d'un dossier.  J'ai noté cela dans les spécifications - voir @fc8c5b2.
