### ISSUE TITLE
Valorisation en page d'accueil (bandeau)

### ISSUE THREAD

**Issue by Julie-JDS** [Jardin-des-Sciences/website#14]
Peut-on mettre en valeur sur la page d'accueil un contenu "ressource patrimoniale" ou "diaporama" ?
Est ce que c'est compliqué par rapport au fait de valoriser un billet / un dossier ?

**Comment by bzg** [comment]
Je ne comprends pas la question : tu veux dire, est-ce qu'on peut mettre en avant une ressources ou un diaporama à la place d'un billet ou d'un dossier ?  Si c'est bien la question, la réponse est « oui, en créant artificiellement un dossier correspondant à la ressource ou au diaporama à valoriser ».  Ce qui fait sens : le but de la valorisation étant, autant que possible, de mettre en avant les contenus « complets ».

Dis-moi si je n'ai pas bien compris la question.

**Comment by Julie-JDS** [comment]
Pourquoi doit-on créer un dossier pour valoriser une ressource ou un diaporama qui sont pourtant déjà des types de contenus distincts ?
Je ne comprends pas " Ce qui fait sens : le but de la valorisation étant, autant que possible, de mettre en avant les contenus « complets »." Un diaporma est "complet", du moins par rapport à un visuel seul. Il peut être complété de légendes pour donner des infos de contexte ou autre.

**Comment by bzg** [comment]
Je te donnais la réponse du point de vue technique.  Pour l'instant il n'est pas prévu de pouvoir mettre en avant autre chose que des billets et des dossiers, donc pour mettre en avant un diaporama il faudra qu'il soit l'élément visuel unique d'un dossier, et qu'on mette en avant le diaporama à travers le dossier.

S'il faut faire autrement, il faut aussi revoir la navigation en une, car les données d'un diaporama ne sont pas celles d'un dossier.
