### ISSUE TITLE
nettoyage de fichiers textes

### ISSUE THREAD

**Issue by Julie-JDS** [Jardin-des-Sciences/website#16]
Si on dispose de contenus qui actuellement sont dans une publication en pdf, et qu'on souhaite en reprendre certains extraits, est-il utile de prévoir un copier-collé word ou pourrons-nous passer directement du pdf en copier-collé sur le formulaire de la plate-forme ? 

Pour un autre projet, je devais "nettoyer" des docs word en passant par le logiciel "markdown" avant de remplir des formulaires pour des publications de textes en ligne.

Comment ça se passerait ici ?

**Comment by bzg** [comment]
Tu pourras faire des copier-coller directement des PDF vers les champs de formulaire des contenus.

Pas besoin de passer du PDF au Word ou du PDF au format Markdown.

Mais en général, il faut éviter tant que possible les copier-coller : cela glisse en douce des éléments de mise en forme (sauts de ligne, gras) qui n'ont rien à faire dans la version finale du texte.  Ou en tous cas il faut être très prudent.
