### ISSUE TITLE
Type de contenu : sondage

### ISSUE THREAD

**Issue by Julie-JDS** [Jardin-des-Sciences/website#18]
Il y a un type de contenu que nous n'avons pas encore détaillé : le "sondage".

L'idée, c'est une question posée par un contributeur, qui pourrait par ex. devenir un contenu constitutif d'un dossier thématique, et cette question solliciterait le public afin qu'il donne son point de vue (sur par ex. une question de société).

Le contributeur choisit parmi trois réponses possibles quel serait son point de vue et peut ensuite voir ce qu'on répondu les autres usagers de la plate-forme en %.

Voici les champs que je suggère pour ce type de contenu.
En vois-tu d'autres ?

Titre
Thème / Champs simple
Question 1
3 réponses
Pages d’affichage des réponses des contributeurs en pourcentage 
(actualisation en continu puisqu'il n'y a pas de date de fin)

**Comment by bzg** [comment]
J'ai créé le type de contenu "sondage" ici : https://github.com/Jardin-des-Sciences/website/blob/master/iteration_1.org#sondage

Comme tu vois, j'ai laissé ouvert le nombre de questions et le nombre de réponses par question.  Je pense que c'est plus souple et utile ainsi, mais dis-moi si tu penses qu'il faut restreindre.

**Comment by Julie-JDS** [comment]
Ok pour le fait de laisser ouvert le nombre de questions.

Par contre, il faudrait préciser l'idée suivante : 
une fois que l'on a donné sa position / son opinion, on peut consulter les réponses données 
par les autres personnes qui ont répondu, l'objectif était de savoir quelle est l'opinion qui ressort 
sur telle ou telle question de société.

J'avais formulé ça comme ça : 
"Pages d’affichage des réponses des contributeurs en pourcentage
(actualisation en continu puisqu'il n'y a pas de date de fin)". 
C'est peut être à reformuler.
Je peux préciser si ce n'est pas clair.

Merci :)

**Comment by bzg** [comment]
Cela figure dans les user stories en tant que "voir les réponses à un sondage".

Pas besoin de mettre cela dans la structure des contenus.
