### ISSUE TITLE
remarques / statistiques

### ISSUE THREAD

**Issue by Julie-JDS** [Jardin-des-Sciences/website#19]
Juste une remarque pour les suggestions de statistiques  :
https://github.com/Jardin-des-Sciences/website/blob/master/specifications.org#administrateurs-1

Tu proposes "répartition des abonnés par thème/disciplines/types de contenus". 
On préfère rester sur "répartition des abonnés par thème".
On se dit que les thèmes proposeront des approches question de société / histoire des sciences 
alors que les disciplines restent sur la dimension uniquement scientifique. 
Par ailleurs, le fait de s'abonner par le critère des types de contenus nous semble également réducteur. 

On souhaite favoriser les visions transversales en incitant à s'abonner aux thèmes uniquement.

Ok pour supprimer "Voir le % de finalisation des dossiers en cours de constitution ".

**Comment by bzg** [comment]
OK, j'ai fait les modifications dans https://github.com/Jardin-des-Sciences/website/commit/4f1168a94f4789ff570d7656d7154264ed394f3e
