### ISSUE TITLE
introduire une nouvelle thématique, une nouvelle discipline

### ISSUE THREAD

**Issue by Issenmann** [Jardin-des-Sciences/website#20]
Bastien, 
J'inaugure le github! il me semble que nous n'avons pas pour le moment pensé dans les user stories et les wire frames à la façon dont on pouvait introduire une nouvelle thématique (autre que biodiversité et sismo) ou une nouvelle discipline, notamment quand le jardin des sciences veut mettre de nouveaux contenus. Cela se gère au niveau de l'admin? 
qu'en penses-tu?
Delphine

**Comment by bzg** [comment]
Oui, bonne question - j'ai ajouté ça à notre document:

https://github.com/Jardin-des-Sciences/website/commit/741e9ad64e9a2f4d2506d4afdaf483a607a777b7

PS: CRUD signifie "Create", "Read", "Update", "Delete" - c'est un acronyme qu'on emploie souvent pour indiquer qu'on veut pouvoir créer/effacer des éléments: https://fr.wikipedia.org/wiki/CRUD
