### ISSUE TITLE
Points complexes - Téléchargement des contenus

### ISSUE THREAD

**Issue by Nicoloye** [Jardin-des-Sciences/website#23]
Le point tel qu'évoqué lors de nos premiers échanges est résumé comme suit:
* Ne sont inclus que les éléments de type image, edito ou texte, sont ignorés les vidéos, les galleries d'images ne sont délivrées que comme une succession d'images sans carroussel JS.
* à la mise à jour d'un dossier le fichier zip est (re)généré via un traitement batch (barre de progression)
* le fichier est ensuite disponible au téléchargement.

Les problèmes potentiels autour de ce point:
* Le temps de génération du zip peut être conséquent après enregistrement du Dossier.
* La définition exacte de ce qui va être dans le fichier est à fixer (dossiers, fichiers, etc), quel usage attendu pour ce contenu (faut-il prévoir un autorun, etc) ?

**Comment by bzg** [comment]
Je propose que les zip soient générés en asynchrone après chaque modification de dossier ou de parcours.  Ces tâches asynchrones seraient stockées dans un système de queueing.

Un temps de trois à quatre heures pour la génération d'un zip après enregistrement des dossiers/parcours me paraît acceptable.

Ensuite le téléchargement du zip n'est plus qu'un lien vers le zip existant, avec téléchargement immédiat.

L'arborescence du fichier zippé serait du type:

```
├── index.html
├── images
│   └── image1.jpg
└── contenus
    └── billet1.html
```
 
PS: Je suppose qu'il existe déjà un système de queueing pour d'autres tâches comme l'indexation, l'envoi des mails, et qu'on peut utiliser ce système en plus pour cela.

@Issenmann pour validation de l'approche.

**Comment by Issenmann** [comment]
ok pour moi. Par contre, pour ce qui concerne les contenus non hébergés sur le site (liens, métadonnées ou vidéos) : on avait imaginé une page html avec tous les éléments du dossiers et qui contient liens vers les contenus non hébergés. Tu me confirmes qu'il s'agit bien du fichier index.html que tu mentionnes?

**Comment by bzg** [comment]
Oui, merci pour la précision: les contenus non-hébergés mais insérés dans les dossiers (typiquement les liens vers une vidéos externe ou un article externe) seraient contenus dans un fichier `.html` du `.zip`.
