### ISSUE TITLE
Points complexes - Tag d'une image

### ISSUE THREAD

**Issue by Nicoloye** [Jardin-des-Sciences/website#24]
La user story 61 précise le point suivant : "ajouter un tag/commentaire à un visuel à un endroit précis"

Ce que je comprends ici c'est à peu de choses près le fait de poser un commentaire après clic sur une visuel. Cela implique plusieurs choses:

* Ce comportement ne concerne que le type de contenu Visuel.
* Il faut définir à quel endroit cela a du sens, car en l'état les visuels ne sont exposés que sur le moteur de recherche et en lien sur un billet ou un visuel.

De mon point de vue ce tagging n'a de sens que depuis une page où le Visuel est exposé directement (une page dédiée avec le visuel en grande taille et son descriptif en dessous). Est-ce que ça fait sens pour vous ?
Je pose essentiellement la question car une telle page n'a pas été maquettée.

**Comment by bzg** [comment]
Cela soulève un point **très important** - @Issenmann pour validation.

Il est clair que _toutes les pages n'ont pas été maquettées_, et qu'il faudra une page dédiée par type de contenu : une page présentant un visuel, une page présentant un sondage, etc.

Je propose qu'on chiffre deux maquettes supplémentaires, chacune servant de matrice pour plusieurs contenus:

- une maquette "média" pour les images, les vidéos, les diaporamas, les sons ;
- une maquette "autres contenus" pour les événements, les sondages, les QCM, les questions éditorialisées, les entrées de glossaire, les FAQ, les liens.

Dis-nous si l'approche te semble raisonnable.

S'il faut sacrifier un type de contenu, nous pouvons en parler.

**Comment by bzg** [comment]
Pour le tagging d'une image en particulier, l'idée est de copier la fonctionnalité proposée sur Facebook: on choisit une zone de l'image et on ajoute une note relative à cette zone.  Cette note est visible par tous les utilisateurs et peut être éditée par celui qui l'a posée.

**Comment by Issenmann** [comment]
ok : à voir l'impact financier, car pour moi moins prioritaire
