### ISSUE TITLE
Points complexes - Tag depuis une sélection d'un texte

### ISSUE THREAD

**Issue by Nicoloye** [Jardin-des-Sciences/website#25]
La user story 62 précise ceci "tagger un contenu texte en surlignant un passage du texte".

Je pense comprendre ici le point de la façon suivante:
* un utilisateur peut poser un commentaire sur un contenu en le basant sur une sélection précise du texte.

Si c'est le cas, les problèmes suivants sont à régler:
* Quelle façon de faire comprendre à l'utilisateur qu'il peut poser de tels commentaires ?
* Qui peut supprimer quel commentaire ? Quelle modération à prévoir ?

Sinon quel était le fonctionnement attendu ?

**Comment by bzg** [comment]
Cette fonctionnalité est partiellement semblable à celle proposée sur https://medium.com où un utilisateur peut sélectionner une zone de texte puis commenter cette zone.

Pour indiquer que cette zone est commentée, elle serait grisée:

- #eeeeee = 1 à 3 commentaires
- #dddddd = 3 à 6 commentaires
- #ccccccc = plus de 6 commentaires

Pour indiquer que cette zone peut être commentée, peut être surligner en #eeeeee les mots sur lesquels le curseur de la souris passe - ou tout autre indice simple.  Au pire, pas d'indice, et ce sera expliqué dans les tutoriels.

Les commentaires sont lisibles par tout le monde et apparaissent dans une fenêtre modale dédiée, les uns à la suite des autres - cette fonction est pour des courts commentaires.

Les commentaires sont modérés par le contributeur du contenu, et ils peuvent être (aussi) effacé par l'utilisateur qui a commenté.

C'est l'idée de départ: toute simplification est possible.

@Issenmann pour confirmation.

**Comment by Issenmann** [comment]
ok pour moi
