### ISSUE TITLE
Itération 3 - Openbadges - Qualificatifs

### ISSUE THREAD

**Issue by Nicoloye** [Jardin-des-Sciences/website#27]
Tels que décrits la façon d'assigner ces qualitatifs est assez floue.
Dans la mesure où ils reposent essentiellement sur des aspects contextuels je pense qu'une assignation manuelle est plus simple, à discuter.

**Comment by Issenmann** [comment]
qu'entend-on précisemment par assignation manuelle?

**Comment by Nicoloye** [comment]
@Issenmann cela signifie qu'un administrateur ou une personne autorisée doit manuellement assigner le qualificatif au contributeur, en accédant à un formulaire dédié lui permettant cette assignation.

**Comment by Issenmann** [comment]
ok!

**Comment by bzg** [comment]
Je pense que l'attribution par les administrateurs peut être mal perçue, elle est un peu infantilisante.

L'idée était que les qualificatifs fonctionnement automatiquement, comme des méta-badges, mais c'est difficile à définir.

Je propose qu'on laisse tomber cette fonctionnalité, déjà marquée comme optionnelle.

**Comment by Issenmann** [comment]
oui, je suis d'accord, concentrons-nous sur plus important ;-)
