### ISSUE TITLE
Point à aborder : affichage aléatoire des billets / dossiers - quel algorithme ?

### ISSUE THREAD

**Issue by Julie-JDS** [Jardin-des-Sciences/website#3]
Comment déterminera-t-on une règle du jeu à ce sujet ?

> par date de publication, en assumant le risque d'un affichage 
plus statique s'il y a peu de contribution au départ.

> par "+ lus" / "+ commentés" / "+ partagés"

Nous aurons besoin d'échanger à ce sujet pour arbitrer.

**Comment by bzg** [comment]
Question ouverte.  Voir @487941d dans les spécifications.

**Comment by bzg** [comment]
En page d'accueil, un affichage aléatoire pondéré sur l'ancienneté des billets et dossiers potentiellement à la une : les billets et dossiers les plus récents ont le plus de chances d'être tirés au hasard.
