### ISSUE TITLE
Itération 3 - Wysiwyg - Edito

### ISSUE THREAD

**Issue by Nicoloye** [Jardin-des-Sciences/website#30]
**Créer un edito et l’éditer en WYSIWYG
Même chose que pour le billet, la seule différence étant que l’édito est forcément associé à un dossier.**

Je ne suis pas sûr de comprendre cet aspect.
On parle juste de mettre à disposition un champ wysiwyg sur le dossier ?

**Comment by bzg** [comment]
> On parle juste de mettre à disposition un champ wysiwyg sur le dossier ?

Non, on parle d'éditer un article de type "billet" en wysiwyg avec un éditeur type [tinymce](https://www.tinymce.com), et de permettre à l'utilisateur de facilement _lier_ ce billet à un dossier pour en faire son edito.

Fonctionnellement, un edito = un billet lié en tant qu'edito à un dossier.

Il peut y avoir plusieurs billets par dossier, mais un seul edito.

**Comment by bzg** [comment]
Si c'est clair ainsi pour @Issenmann aussi nous pouvons clore le ticket.

**Comment by Issenmann** [comment]
ok!

**Comment by Nicoloye** [comment]
Je pense que nous disons la même chose avec un vocable différent, nous verrons le diff à la recette. Je pense qu'on peut clore le ticket.

**Comment by bzg** [comment]
C'est clos, merci.
