### ISSUE TITLE
Itération 3 - Wysiwyg - Diaporama

### ISSUE THREAD

**Issue by Nicoloye** [Jardin-des-Sciences/website#31]
L'accompagnement des images par un son est-il réellement nécessaire ?
Il y a assez peu de librairies JS qui supportent le son nativement, si c'est un aspect important il faudra trouver une librairie adaptée.

Le timer est en général appliqué à l'ensemble du slider, pas à une slide précise, là aussi si c'est un impératif il faudra trouver une librairie compatible.

Le traitement de formats .pdf, .pptx ou .odp pour extraction d'une série d'image serait un chantier extrêmement couteux à mettre en place.

**Comment by bzg** [comment]
OK. Je propose qu'on simplifie et qu'on rende simplement naviguable les documents de type "présentation", à savoir .pdf, pptx, odp.

Il y a http://viewerjs.org/examples/ - @Issenmann je te laisse regarder pour voir si ça répondrait au besoin.

**Comment by Issenmann** [comment]
ok pour moi.

**Comment by Nicoloye** [comment]
OK, nous utiliserons donc https://www.drupal.org/project/viewerjs

**Comment by Nicoloye** [comment]
Pour le slider visible sur une page Dossier ou Billet par contre il faudra sans doute prévoir un champ pour une miniature de preview.

**Comment by Issenmann** [comment]
ok, bonne suggestion

**Comment by bzg** [comment]
C'est noté - je ferme le ticket.
