### ISSUE TITLE
Points Complexes - Accessibilité

### ISSUE THREAD

**Issue by Nicoloye** [Jardin-des-Sciences/website#33]
L'accessibilité sera une contrainte complexe a mettre en oeuvre dans le cadre d'un site ouvert à la contribution publique. Ceci dans la mesure où une bonne partie de l'accessibilité repose sur la qualité des contenus saisis.
Nous pouvons mettre en place une base d'outils standards mais nos actions seront vite limités.

**Comment by bzg** [comment]
Je dirais que nous avons ici une obligation de _moyens_ pour rendre accessibles les contenus contribués et les données importées, et de _résultats_ pour que l'infrastructure du site (sans les contenus contribués ni les données importées) soit accessible : c'était surtout un "reminder" pour penser à expliciter et chiffrer les actions liées.

**Comment by bzg** [comment]
@Issenmann pour validation.

**Comment by Issenmann** [comment]
ok avec la remarque de Bastien
