### ISSUE TITLE
Champ commun pour les contenus connexes

### ISSUE THREAD

**Issue by Winde4th** [Jardin-des-Sciences/website#34]
Pour certains types de contenus comme "Dossier" ou "Billet", on a autant de champs "XXXX connexes" que de types de contenus,
- Dossiers connexes
- Billets connexes
- Visuels connexes
- Vidéos connexes
- etc.

Pourrait-on proposer de n'utiliser qu'un seul champ "Contenus connexes", puis faire le filtre ensuite dans ce champ à l'affichage des différentes pages pour ne sélectionner que les types de contenus souhaités ?

Les avantages :
- La saisie est facilité : il n'y a pas besoin de savoir à l'avance quel est le type du contenu que l'on veut relier 
- Le datamodel est un peu simplifié / allégé 
- Si plus tard on ajoutait un nouveau type de contenu, on n'aurait pas à repasser partout pour adapter

Les inconvénients : 
- L'ordonnancement des contenus liés sera moins facile / moins lisible dès qu'il commence à y avoir beaucoup d'entrées
- Cela peut provoquer quelques confusions au niveau de l'autocomplétion au moment de la saisie, si 2 contenus de types différents ont le même intitulé par exemple (l'identifiant est indiqué à côté mais cela n'est pas forcément évident...)

**Comment by bzg** [comment]
Oui.
