### ISSUE TITLE
Question : type de contenus - ressources documentaires

### ISSUE THREAD

**Issue by Julie-JDS** [Jardin-des-Sciences/website#5]
Est-ce qu'il suffit de catégoriser les ressources documentaires par un champ descriptif pour distinguer parmi elles

- les notices patrimoniales (nom à préciser)
- les documents d'archives
- les thèses et mémoires
- les bibliographie
- les articles scientifiques
- les fiches pédagogiques (nom à préciser)

?

A priori, ces contenus seront en pdf ou en format visuel (numérisation)  sauf les notices patrimoniales et peut être les bibliographies dont je ne sais pas encore à quoi elle ressembleront.

**Comment by bzg** [comment]
Nous devons intégrer ces champs à la description du type de contenu "ressource documentaire" - travail en cours.

**Comment by bzg** [comment]
Il faudra faire la liste des types de ressources mais oui, ce champ est dans les Ressources documentaires et dans les visuels.

**Comment by Julie-JDS** [comment]
Je reprends cette issue afin de voir si nous avons des aspects à préciser à présent sur cette question.
Reparlons-en.

**Comment by bzg** [comment]
Je propose d'utiliser les mots-clefs (avec complétion sur les mots-clefs existants) pour ces distinctions.
