### ISSUE TITLE
Question : type de contenus - Interface questions - FAQ

### ISSUE THREAD

**Issue by Julie-JDS** [Jardin-des-Sciences/website#6]
Attention à distinguer : 

> Questions / réponses : 
interface interactive entre grand public et chercheurs / médiateurs où on pose des questions de sciences et où on peut obtenir une réponse vulgarisée.
(Est-il envisageable à défaut de développer une interface complexe d'envisager de pouvoir se filmer et poster la question ou la réponse en ligne ? Complexité ?)

et 

> FAQ : interface pratique avec formulaire permettant de formuler une question / interface avec formulaire permettant de répondre sur des thématiques liées au fonctionnement du site par ex.
(La question d'un forum reste à envisager.)

**Comment by bzg** [comment]
La distinction est bien notée dans le cahier des charges.

Je pense qu'un jeu de questions / réponses en vidéo est trop lourd à mettre en place : tout ce qui a trait à l'édition de vidéo demande beaucoup de moyens.
